-- Staging-only helper. Replace @account_id with an existing v3 account ID.
-- Run in a disposable database clone.
SET @account_id = 1;
INSERT INTO renewed_bank_transactions
(group_id, request_id, account_id, direction, transaction_type, amount, balance_before, balance_after, actor_identifier, counterparty_ref, description, metadata, created_at)
SELECT
  CONCAT('perf-', seq), CONCAT('perf-request-', seq), @account_id,
  IF(MOD(seq, 2) = 0, 'credit', 'debit'), 'performance_seed', 1,
  NULL, NULL, 'performance', 'seed', 'Statement pagination seed', '{}',
  DATE_SUB(CURRENT_TIMESTAMP(3), INTERVAL seq SECOND)
FROM (
  SELECT a.N + b.N * 10 + c.N * 100 + d.N * 1000 + e.N * 10000 + 1 AS seq
  FROM (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) d
  CROSS JOIN (SELECT 0 N UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
) sequence_rows
WHERE seq <= 100000;
