RenewedBanking = RenewedBanking or {}
local RB = RenewedBanking
RB.VERSION = '3.0.0-rc.1'
RB.AccountTypes = { PERSONAL = 'personal', JOB = 'job', GANG = 'gang', SHARED = 'shared', SYSTEM = 'system', ADMIN = 'admin' }
RB.AccountStatuses = { ACTIVE = 'active', FROZEN = 'frozen', CLOSED = 'closed', MIGRATION_HOLD = 'migration_hold' }
RB.Actions = { VIEW = 'view', DEPOSIT = 'deposit', WITHDRAW = 'withdraw', TRANSFER = 'transfer', MEMBERS = 'members', RENAME = 'rename', CLOSE = 'close', FREEZE = 'freeze', ADMIN_ADJUST = 'admin_adjust' }
RB.Roles = { OWNER = 'owner', ADMIN = 'admin', OPERATOR = 'operator', VIEWER = 'viewer' }
RB.Errors = {
    PLAYER_NOT_LOADED = 'PLAYER_NOT_LOADED', INVALID_PAYLOAD = 'INVALID_PAYLOAD', INVALID_AMOUNT = 'INVALID_AMOUNT',
    AMOUNT_TOO_LARGE = 'AMOUNT_TOO_LARGE', INVALID_ACCOUNT_KEY = 'INVALID_ACCOUNT_KEY', INVALID_REQUEST_ID = 'INVALID_REQUEST_ID',
    ACCOUNT_NOT_FOUND = 'ACCOUNT_NOT_FOUND', RECIPIENT_NOT_FOUND = 'RECIPIENT_NOT_FOUND', SAME_ACCOUNT = 'SAME_ACCOUNT',
    UNAUTHORIZED = 'UNAUTHORIZED', ACCOUNT_FROZEN = 'ACCOUNT_FROZEN', ACCOUNT_CLOSED = 'ACCOUNT_CLOSED',
    MIGRATION_REQUIRED = 'MIGRATION_REQUIRED', INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS', RATE_LIMITED = 'RATE_LIMITED',
    REQUEST_IN_PROGRESS = 'REQUEST_IN_PROGRESS', IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
    FRAMEWORK_OPERATION_FAILED = 'FRAMEWORK_OPERATION_FAILED', DATABASE_OPERATION_FAILED = 'DATABASE_OPERATION_FAILED',
    SETTLEMENT_PENDING = 'SETTLEMENT_PENDING', SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',
    ACCOUNT_LIMIT_REACHED = 'ACCOUNT_LIMIT_REACHED', ACCOUNT_NOT_EMPTY = 'ACCOUNT_NOT_EMPTY',
    MEMBER_EXISTS = 'MEMBER_EXISTS', MEMBER_NOT_FOUND = 'MEMBER_NOT_FOUND', LAST_OWNER = 'LAST_OWNER'
}
